name: build

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
          cache: pip
          cache-dependency-path: 'requirements-dev.txt'

      - name: Install Python dependencies
        run: make install-dev

      - name: Run lint checks
        run: make lint

  test:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout data
        uses: actions/checkout@v4
        with:
          repository: techmatters/soil-id-data
          path: Data
          lfs: true

      - name: Create LFS file list
        working-directory: Data
        run: git lfs ls-files --long | cut -d ' ' -f1 | sort > .lfs-assets-id

      - name: Restore LFS Cache
        uses: actions/cache@v4
        with:
          path: Data/.git/lfs/objects
          key: ${{ runner.os }}-lfs-${{ hashFiles('.lfs-assets-id') }}
          restore-keys: ${{ runner.os }}-lfs-

      - name: Git LFS Pull
        working-directory: Data
        run: git lfs pull

      - name: Update and install Linux packages
        run: |
          sudo apt-get update
          sudo apt-get install libgdal-dev gdal-bin python3-gdal

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.2"
          cache: pip
          cache-dependency-path: 'requirements.txt'

      - name: Install Python dependencies
        run: make install-dev && make install-no-deps

      - name: Run tests
        run: make test
